# Generated by Django 4.0.6 on 2022-07-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(max_length=50)),
                ('to_date', models.DateField(max_length=50)),
                ('person_id', models.CharField(max_length=10)),
                ('offense_id', models.CharField(max_length=10)),
            ],
        ),
    ]
