# Generated by Django 4.0.6 on 2022-07-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convicts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convicts',
            name='offense_id',
            field=models.IntegerField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='convicts',
            name='person_id',
            field=models.IntegerField(max_length=50000),
        ),
    ]
