# Generated by Django 4.0.5 on 2022-07-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Convicts', '0003_alter_convicts_from_date_alter_convicts_offense_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convicts',
        ),
    ]
