# Generated by Django 4.0.5 on 2022-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persons', '0002_remove_person_id_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
    ]
