# Generated by Django 4.0.5 on 2022-07-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Persons', '0003_alter_person_id_alter_person_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
