# Generated by Django 4.0.6 on 2022-07-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(max_length=50)),
                ('size', models.IntegerField(max_length=50000)),
            ],
        ),
    ]
