# Generated by Django 4.0.6 on 2022-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dungeon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='size',
            field=models.IntegerField(),
        ),
    ]
