# Generated by Django 4.0.5 on 2022-07-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dungeon', '0002_alter_dungeon_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dungeon',
        ),
    ]
