# Generated by Django 4.0.6 on 2022-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dungeon_Moves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon_moves',
            name='dungeon_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dungeon_moves',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dungeon_moves',
            name='person_id',
            field=models.IntegerField(),
        ),
    ]
