# Generated by Django 4.0.5 on 2022-07-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_alter_convicts_id_alter_dungeon_moves_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='size',
            field=models.BigIntegerField(),
        ),
    ]
