# Generated by Django 4.0.5 on 2022-07-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0003_alter_dungeon_name_alter_dungeon_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dungeon',
            old_name='Id',
            new_name='dungeon_id',
        ),
        migrations.RenameField(
            model_name='offense',
            old_name='Id',
            new_name='offense_id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Id',
            new_name='person_id',
        ),
        migrations.RemoveField(
            model_name='convicts',
            name='Id',
        ),
        migrations.RemoveField(
            model_name='dungeon_moves',
            name='Id',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='Id',
        ),
        migrations.AddField(
            model_name='convicts',
            name='offense_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Classes.offense', verbose_name='Offense ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convicts',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Classes.person', verbose_name='Person ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dungeon_moves',
            name='dungeon_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Classes.dungeon', verbose_name='Dungeon ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dungeon_moves',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Classes.person', verbose_name='Person ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Classes.person', verbose_name='Person ID'),
            preserve_default=False,
        ),
    ]
