# Generated by Django 4.0.5 on 2022-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0004_rename_id_dungeon_dungeon_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convicts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dungeon_moves',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='id',
        ),
        migrations.AddField(
            model_name='convicts',
            name='convicts_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dungeon_moves',
            name='dungeon_moves_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visits',
            name='visits_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='dungeon_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='offense',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='offense',
            name='offense_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
