# Generated by Django 4.0.6 on 2022-07-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0005_remove_convicts_id_remove_dungeon_moves_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.DateField(max_length=10),
        ),
    ]
