# Generated by Django 4.0.6 on 2022-07-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0006_alter_person_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.DateField(blank=True),
        ),
    ]
