# Generated by Django 4.0.5 on 2022-07-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offense', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offense',
        ),
    ]
