# Generated by Django 4.0.6 on 2022-07-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateField()),
                ('person_id', models.IntegerField(max_length=50000)),
                ('visitor_name', models.CharField(max_length=50)),
                ('mount_in_minutes', models.IntegerField()),
            ],
        ),
    ]
