# Generated by Django 4.0.5 on 2022-07-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0002_alter_visits_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='v',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='visits',
            name='person_id',
        ),
        migrations.AddField(
            model_name='visits',
            name='Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Visits.v', verbose_name='the related Person'),
            preserve_default=False,
        ),
    ]
