# Generated by Django 4.0.5 on 2022-07-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visits', '0003_v_remove_visits_person_id_visits_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='Id',
        ),
        migrations.DeleteModel(
            name='v',
        ),
        migrations.DeleteModel(
            name='Visits',
        ),
    ]
